version: "3.8"

services:

  mongodb:
    image: bitnami/mongodb:4.4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: gamescoredb
      MONGODB_USERNAME: gamescoreuser
      MONGODB_PASSWORD: gamescorepass
      MONGODB_ROOT_PASSWORD: secret
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookdb --quiet
      start_period: 10s
