spring:
  application:
    name: game-score-api
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: gamescoredb

collector:
  mode: GET_AND_SAVE
  website:
    url: http://www.metacritic.com/browse/games/release-date/available/ps4/metascore
    min-page: 0
    max-page: 9
