spring:
  application:
    name: game-score-api
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/gamescoredb

collector:
  mode: GET_AND_SAVE
  website:
    url: http://www.metacritic.com/browse/games/release-date/available/ps4/metascore
    min-page: 0
    max-page: 9
