spring:
  application:
    name: game-score-api
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/gamescoredb

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
